name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'spec/**'
      - 'examples/**'
      - 'shard.yml'
      - 'scripts/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'spec/**'
      - 'examples/**'
      - 'shard.yml'
      - 'scripts/**'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crystal-version:
          - "1.16.3"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Crystal
      uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ matrix.crystal-version }}

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/shards
        key: ${{ runner.os }}-shards-${{ hashFiles('shard.yml') }}
        restore-keys: ${{ runner.os }}-shards-

    - name: Install dependencies
      run: shards install

    - name: Run type check
      run: crystal build src/obelisk.cr --no-codegen

    - name: Run specs
      run: ./scripts/test.sh no-coverage

    - name: Run examples
      run: |
        for example in examples/*.cr; do
          echo "Running $example"
          crystal run "$example"
        done

  format:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Crystal
      uses: crystal-lang/install-crystal@v1
      with:
        crystal: "1.16.3"

    - name: Check formatting
      run: crystal tool format --check

  coverage:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Crystal
      uses: crystal-lang/install-crystal@v1
      with:
        crystal: "1.16.3"

    - name: Install kcov
      run: |
        sudo apt-get update &&
        sudo apt-get install binutils-dev libssl-dev libcurl4-openssl-dev libelf-dev libstdc++-12-dev zlib1g-dev libdw-dev libiberty-dev
        curl -L -o ./kcov.tar.gz https://github.com/SimonKagstrom/kcov/archive/refs/tags/v43.tar.gz &&
        mkdir kcov-source &&
        tar xzf kcov.tar.gz -C kcov-source --strip-components=1 &&
        cd kcov-source &&
        mkdir build &&
        cd build &&
        cmake .. &&
        make -j$(nproc) &&
        sudo make install

    - name: Install dependencies
      run: shards install

    - name: Run specs with coverage
      run: ./scripts/test.sh with-coverage

    - name: Debug coverage files
      run: |
        echo "Coverage directory contents:"
        ls -la coverage/
        echo "Coverage report directory contents:"
        ls -la coverage/report/ || echo "coverage/report/ doesn't exist"

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/report/
        files: "*.xml,*.json"
        fail_ci_if_error: false

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Crystal
      uses: crystal-lang/install-crystal@v1
      with:
        crystal: "1.16.3"

    - name: Install dependencies
      run: shards install

    - name: Build release binary
      run: crystal build src/obelisk.cr --release

    - name: Test compiled binary
      run: ./obelisk --help || echo "Binary built successfully (no CLI yet)"